Remove-Item -Path  "./packages/alert/dist" -Force -Recurse
Remove-Item -Path  "./packages/app-bar/dist" -Force -Recurse
Remove-Item -Path  "./packages/autocomplete/dist" -Force -Recurse
Remove-Item -Path  "./packages/avatar/dist" -Force -Recurse
Remove-Item -Path  "./packages/badge/dist" -Force -Recurse
Remove-Item -Path  "./packages/button/dist" -Force -Recurse
Remove-Item -Path  "./packages/card/dist" -Force -Recurse
Remove-Item -Path  "./packages/chip/dist" -Force -Recurse
Remove-Item -Path  "./packages/codemod/dist" -Force -Recurse
Remove-Item -Path  "./packages/dev-utils/dist" -Force -Recurse
Remove-Item -Path  "./packages/dialog/dist" -Force -Recurse
Remove-Item -Path  "./packages/divider/dist" -Force -Recurse
Remove-Item -Path  "./packages/documentation/dist" -Force -Recurse
Remove-Item -Path  "./packages/elevation/dist" -Force -Recurse
Remove-Item -Path  "./packages/expansion-panel/dist" -Force -Recurse
Remove-Item -Path  "./packages/form/dist" -Force -Recurse
Remove-Item -Path  "./packages/icon/dist" -Force -Recurse
Remove-Item -Path  "./packages/layout/dist" -Force -Recurse
Remove-Item -Path  "./packages/link/dist" -Force -Recurse
Remove-Item -Path  "./packages/list/dist" -Force -Recurse
Remove-Item -Path  "./packages/material-icons/dist" -Force -Recurse
Remove-Item -Path  "./packages/media/dist" -Force -Recurse
Remove-Item -Path  "./packages/menu/dist" -Force -Recurse
Remove-Item -Path  "./packages/overlay/dist" -Force -Recurse
Remove-Item -Path  "./packages/portal/dist" -Force -Recurse
Remove-Item -Path  "./packages/progress/dist" -Force -Recurse
Remove-Item -Path  "./packages/react/dist" -Force -Recurse
Remove-Item -Path  "./packages/react-md/dist" -Force -Recurse
Remove-Item -Path  "./packages/sheet/dist" -Force -Recurse
Remove-Item -Path  "./packages/states/dist" -Force -Recurse
Remove-Item -Path  "./packages/table/dist" -Force -Recurse
Remove-Item -Path  "./packages/tabs/dist" -Force -Recurse
Remove-Item -Path  "./packages/theme/dist" -Force -Recurse
Remove-Item -Path  "./packages/tooltip/dist" -Force -Recurse
Remove-Item -Path  "./packages/transition/dist" -Force -Recurse
Remove-Item -Path  "./packages/tree/dist" -Force -Recurse
Remove-Item -Path  "./packages/typography/dist" -Force -Recurse
Remove-Item -Path  "./packages/utils/dist" -Force -Recurse

Remove-Item -Path  "./packages/alert/types" -Force -Recurse
Remove-Item -Path  "./packages/app-types/dist" -Force -Recurse
Remove-Item -Path  "./packages/autocomplete/types" -Force -Recurse
Remove-Item -Path  "./packages/avatar/types" -Force -Recurse
Remove-Item -Path  "./packages/badge/types" -Force -Recurse
Remove-Item -Path  "./packages/button/types" -Force -Recurse
Remove-Item -Path  "./packages/card/types" -Force -Recurse
Remove-Item -Path  "./packages/chip/types" -Force -Recurse
Remove-Item -Path  "./packages/codemod/types" -Force -Recurse
Remove-Item -Path  "./packages/dev-types/dist" -Force -Recurse
Remove-Item -Path  "./packages/dialog/types" -Force -Recurse
Remove-Item -Path  "./packages/divider/types" -Force -Recurse
Remove-Item -Path  "./packages/documentation/types" -Force -Recurse
Remove-Item -Path  "./packages/elevation/types" -Force -Recurse
Remove-Item -Path  "./packages/expansion-types/dist" -Force -Recurse
Remove-Item -Path  "./packages/form/types" -Force -Recurse
Remove-Item -Path  "./packages/icon/types" -Force -Recurse
Remove-Item -Path  "./packages/layout/types" -Force -Recurse
Remove-Item -Path  "./packages/link/types" -Force -Recurse
Remove-Item -Path  "./packages/list/types" -Force -Recurse
Remove-Item -Path  "./packages/material-types/dist" -Force -Recurse
Remove-Item -Path  "./packages/media/types" -Force -Recurse
Remove-Item -Path  "./packages/menu/types" -Force -Recurse
Remove-Item -Path  "./packages/overlay/types" -Force -Recurse
Remove-Item -Path  "./packages/portal/types" -Force -Recurse
Remove-Item -Path  "./packages/progress/types" -Force -Recurse
Remove-Item -Path  "./packages/react/types" -Force -Recurse
Remove-Item -Path  "./packages/react-types/dist" -Force -Recurse
Remove-Item -Path  "./packages/sheet/types" -Force -Recurse
Remove-Item -Path  "./packages/states/types" -Force -Recurse
Remove-Item -Path  "./packages/table/types" -Force -Recurse
Remove-Item -Path  "./packages/tabs/types" -Force -Recurse
Remove-Item -Path  "./packages/theme/types" -Force -Recurse
Remove-Item -Path  "./packages/tooltip/types" -Force -Recurse
Remove-Item -Path  "./packages/transition/types" -Force -Recurse
Remove-Item -Path  "./packages/tree/types" -Force -Recurse
Remove-Item -Path  "./packages/typography/types" -Force -Recurse
Remove-Item -Path  "./packages/utils/types" -Force -Recurse